# Fonts
disable_ligatures always

# Cursor
cursor #cccccc
cursor_text_color #111111
cursor_shape block
cursor_blink_interval 0
cursor_trail 1
shell_integration no-cursor

# Bell
enable_audio_bell no

# Mouse
mouse_hide_wait -1.0
