#!/bin/bash

xsetroot -cursor_name left_ptr &
xset r rate 250 30

pgrep -x sxhkd > /dev/null || sxhkd &

polybar.sh &
dunst.sh &
policykit.sh &
nightlight.sh &
nitrogen --restore &
picom -b &
gwe --hide-window &
xss-lock --transfer-sleep-lock -- lockscreen.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false

. ~/.config/bspwm/appearance
